version: '3.8'
services:
  binance_bot:
    build: .
    command: python -m core.binance_bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
  supervisor_bot:
    build: .
    command: python -m core.supervisor_bot
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
